menu:
  Home: /
  Archive: /archives/
  About: /post/about.html
  GitHub: https://github.com/xuexb/hexo-theme-mip

favicon: /favicon.ico

# Copyright Infomation
startyear: 2017

mip:
  cssmin: false
  css:
    reset.css
    nav.css
    article.css
    main.css
    highlight.css
    footer.css
    pagination.css
